using System.Text;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json → api.endpoints 生成客户端 API 路由常量（SpecRoutes.g.cs）。
///
/// 目标：消除 ApiClient 中的路由魔数字符串（16 处 "/api/..." 字面量），业务层只写参数绑定。
/// 路由常量与 SpecEndpoints（ManifestGenerator 生成）同源于 spec api.endpoints，并引用
/// SpecEndpoints 做交叉校验（DiffAgainstSpecEndpoints），保证两端注册表一致。
/// 纳入 --verify：spec 改端点后生成内容变化即被检出，重跑 CodeGen 后 ApiClient 全链路生效。
///
/// 渐进项：完整客户端方法骨架（从 endpoints 生成 IApiClient 方法签名）留待后续批次，
/// 本生成器先落地「路由常量 + 交叉校验」最小闭环。
/// </summary>
public static class ApiClientGenerator
{
    public static string Generate(SpecDocument spec)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine("// 源: shared-spec.json → api.endpoints（路由常量，与 SpecEndpoints 同源）")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Contract;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 客户端 API 路由常量。由 ApiClientGenerator 从 shared-spec.json → api.endpoints 生成。");
        sb.AppendLine("/// 与 SpecEndpoints（ContractManifest.g.cs）同源：业务层（ApiClient）只写参数绑定，");
        sb.AppendLine("/// 禁止硬编码 \"/api/...\" 路由字面量——改 spec 端点后重跑 CodeGen 即全链路生效。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SpecRoutes");
        sb.AppendLine("{");

        foreach (var ep in spec.Api.Endpoints)
        {
            string name = ToConstantName(ep.Path);
            string method = ep.Method.ToUpperInvariant();
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {EscapeString(ep.Description)}（{method} {ep.Path}）");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public const string {name} = \"{ep.Path}\";");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>(路由常量名, HTTP 方法, 路径) 索引，供 DiffAgainstSpecEndpoints 交叉校验。</summary>");
        sb.AppendLine("    private static readonly (string Name, string Method, string Path)[] RouteIndex =");
        sb.AppendLine("    {");
        foreach (var ep in spec.Api.Endpoints)
        {
            string name = ToConstantName(ep.Path);
            string method = ep.Method.ToUpperInvariant();
            sb.AppendLine($"        (\"{name}\", \"{method}\", \"{ep.Path}\"),");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 与 SpecEndpoints 注册表（ContractManifest.g.cs）交叉校验：");
        sb.AppendLine("    /// 确认每条路由常量对应 (method, path) 均已在 shared-spec.json api.endpoints 注册。");
        sb.AppendLine("    /// 返回不一致描述列表，空表示全部一致。");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static List<string> DiffAgainstSpecEndpoints()");
        sb.AppendLine("    {");
        sb.AppendLine("        var diffs = new List<string>();");
        sb.AppendLine("        foreach (var (name, method, path) in RouteIndex)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 模板参数（如 {shareId}）归一化为 {x}，与 SpecEndpoints.Find 语义一致");
        sb.AppendLine("            var normalized = System.Text.RegularExpressions.Regex.Replace(path, @\"\\{[^}]+\\}\", \"{x}\");");
        sb.AppendLine("            if (SpecEndpoints.Find(method, normalized) is null)");
        sb.AppendLine("            {");
        sb.AppendLine("                diffs.Add($\"{name}: ({method} {path}) 未在 SpecEndpoints 注册\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        return diffs;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// 路由路径 → 常量名：/api/files/tree → FilesTree；
    /// /api/shares/{shareId} → SharesByShareId（模板段前加 By）；/pair → Pair。
    /// 去掉首位 api 段（路由前缀隐含，避免冗余）。
    /// </summary>
    private static string ToConstantName(string path)
    {
        string[] segments = path.Split('/', StringSplitOptions.RemoveEmptyEntries);
        if (segments.Length > 0 && string.Equals(segments[0], "api", StringComparison.OrdinalIgnoreCase))
        {
            segments = segments[1..];
        }

        StringBuilder sb = new StringBuilder();
        foreach (string seg in segments)
        {
            if (seg.StartsWith('{') && seg.EndsWith('}'))
            {
                sb.Append("By").Append(ToPascalCase(seg[1..^1]));
            }
            else
            {
                sb.Append(ToPascalCase(seg));
            }
        }
        return sb.ToString();
    }

    /// <summary>段 → PascalCase：cert-fingerprint → CertFingerprint（按 -/_ 分词）。</summary>
    private static string ToPascalCase(string segment)
    {
        StringBuilder sb = new StringBuilder();
        foreach (string word in segment.Split('-', '_'))
        {
            if (word.Length == 0)
            {
                continue;
            }

            sb.Append(char.ToUpperInvariant(word[0]));
            if (word.Length > 1)
            {
                sb.Append(word[1..]);
            }
        }
        return sb.ToString();
    }

    private static string EscapeString(string s) => s.Replace("\"", "\\\"");
}
