using System.Text;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json → api.endpoints 生成客户端 API 路由常量（SpecRoutes.g.cs）。
///
/// 目标：消除 ApiClient 中的路由魔数字符串（16 处 "/api/..." 字面量），业务层只写参数绑定。
/// 路由常量与 SpecEndpoints（ManifestGenerator 生成）同源于 spec api.endpoints，并引用
/// SpecEndpoints 做交叉校验（DiffAgainstSpecEndpoints），保证两端注册表一致。
/// 纳入 --verify：spec 改端点后生成内容变化即被检出，重跑 CodeGen 后 ApiClient 全链路生效。
///
/// T-086：本类扩展生成 C# 客户端接口签名（GenerateClientInterface → ClientApi.g.cs）与
/// ApiClient 方法骨架（GenerateClientClass → ApiClient.g.cs），均从 api.endpoints[].clientMethod
/// 驱动，纳入同一 --verify 管线。方法渲染细节委托 ClientApiRenderer（保持本类 ≤ 400 行）。
/// </summary>
public static class ApiClientGenerator
{
    public static string Generate(SpecDocument spec)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine("// 源: shared-spec.json → api.endpoints（路由常量，与 SpecEndpoints 同源）")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Contract;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// API 路由常量。由 ApiClientGenerator 从 shared-spec.json → api.endpoints 生成。");
        sb.AppendLine("/// 与 SpecEndpoints（ContractManifest.g.cs）同源：客户端 ApiClient 与服务端");
        sb.AppendLine("/// Controller/Program 共用，禁止硬编码 \"/api/...\" 或 \"/ws\" 路由字面量");
        sb.AppendLine("/// ——改 spec 端点后重跑 CodeGen 即全链路生效。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SpecRoutes");
        sb.AppendLine("{");

        // 同 path 多 HTTP 方法消歧（T-112）：非首个方法常量名追加方法后缀
        // （POST /api/shares → Shares 保持原名，GET /api/shares → SharesGet），C#/Kotlin 两端同规则
        var routeEntries = BuildRouteEntries(spec);

        foreach (var (name, method, path, description) in routeEntries)
        {
            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// {EscapeString(description)}（{method} {path}）");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public const string {name} = \"{path}\";");
            sb.AppendLine();
        }

        sb.AppendLine("    /// <summary>(路由常量名, HTTP 方法, 路径) 索引，供 DiffAgainstSpecEndpoints 交叉校验。</summary>");
        sb.AppendLine("    private static readonly (string Name, string Method, string Path)[] RouteIndex =");
        sb.AppendLine("    {");
        foreach (var (name, method, path, _) in routeEntries)
        {
            sb.AppendLine($"        (\"{name}\", \"{method}\", \"{path}\"),");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// 与 SpecEndpoints 注册表（ContractManifest.g.cs）交叉校验：");
        sb.AppendLine("    /// 确认每条路由常量对应 (method, path) 均已在 shared-spec.json api.endpoints 注册。");
        sb.AppendLine("    /// 返回不一致描述列表，空表示全部一致。");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static List<string> DiffAgainstSpecEndpoints()");
        sb.AppendLine("    {");
        sb.AppendLine("        var diffs = new List<string>();");
        sb.AppendLine("        foreach (var (name, method, path) in RouteIndex)");
        sb.AppendLine("        {");
        sb.AppendLine("            // 模板参数（如 {shareId}）归一化为 {x}，与 SpecEndpoints.Find 语义一致");
        sb.AppendLine("            var normalized = System.Text.RegularExpressions.Regex.Replace(path, @\"\\{[^}]+\\}\", \"{x}\");");
        sb.AppendLine("            if (SpecEndpoints.Find(method, normalized) is null)");
        sb.AppendLine("            {");
        sb.AppendLine("                diffs.Add($\"{name}: ({method} {path}) 未在 SpecEndpoints 注册\");");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        return diffs;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// 路由路径 → 常量名：/api/files/tree → FilesTree；
    /// /api/shares/{shareId} → SharesByShareId（模板段前加 By）；/pair → Pair。
    /// 去掉首位 api 段（路由前缀隐含，避免冗余）。
    /// </summary>
    private static string ToConstantName(string path)
    {
        // /ws 特例：WebSocket 端点缩写，映射为 WebSocket（避免生成含义模糊的 Ws）
        if (string.Equals(path, "/ws", StringComparison.OrdinalIgnoreCase))
        {
            return "WebSocket";
        }

        string[] segments = path.Split('/', StringSplitOptions.RemoveEmptyEntries);
        if (segments.Length > 0 && string.Equals(segments[0], "api", StringComparison.OrdinalIgnoreCase))
        {
            segments = segments[1..];
        }

        StringBuilder sb = new StringBuilder();
        foreach (string seg in segments)
        {
            if (seg.StartsWith('{') && seg.EndsWith('}'))
            {
                sb.Append("By").Append(ToPascalCase(seg[1..^1]));
            }
            else
            {
                sb.Append(ToPascalCase(seg));
            }
        }
        return sb.ToString();
    }

    /// <summary>段 → PascalCase：cert-fingerprint → CertFingerprint（按 -/_ 分词）。</summary>
    private static string ToPascalCase(string segment)
    {
        StringBuilder sb = new StringBuilder();
        foreach (string word in segment.Split('-', '_'))
        {
            if (word.Length == 0)
            {
                continue;
            }

            sb.Append(char.ToUpperInvariant(word[0]));
            if (word.Length > 1)
            {
                sb.Append(word[1..]);
            }
        }
        return sb.ToString();
    }

    private static string EscapeString(string s) => s.Replace("\"", "\\\"");

    /// <summary>
    /// 生成 (常量名, HTTP 方法, 路径, 描述) 路由条目列表。
    /// 同 path 多 HTTP 方法时，非首个方法常量名追加方法后缀（如 GET /api/shares → SharesGet），
    /// 首个方法保持原名（POST /api/shares → Shares，向后兼容）。C#/Kotlin 两端同规则（T-112）。
    /// </summary>
    private static List<(string Name, string Method, string Path, string Description)> BuildRouteEntries(SpecDocument spec)
    {
        var entries = new List<(string, string, string, string)>();
        var methodSeq = new Dictionary<string, int>();
        foreach (var ep in spec.Api.Endpoints)
        {
            int seq = methodSeq.GetValueOrDefault(ep.Path, 0);
            methodSeq[ep.Path] = seq + 1;
            string name = seq == 0
                ? ToConstantName(ep.Path)
                : ToConstantName(ep.Path) + MethodSuffix(ep.Method);
            entries.Add((name, ep.Method.ToUpperInvariant(), ep.Path, ep.Description));
        }
        return entries;
    }

    /// <summary>HTTP 方法 → 常量名后缀（GET → Get，POST → Post，DELETE → Delete 等）。</summary>
    private static string MethodSuffix(string method) => method.ToUpperInvariant() switch
    {
        "GET" => "Get",
        "POST" => "Post",
        "PUT" => "Put",
        "DELETE" => "Delete",
        "PATCH" => "Patch",
        _ => method[..1] + method[1..].ToLowerInvariant()
    };

    // ============================================================
    // 客户端接口签名生成（T-086）
    // ============================================================

    /// <summary>
    /// 生成 C# 客户端接口签名（CloudPan.Contract/Generated/ClientApi.g.cs）。
    /// 从 shared-spec.json → api.endpoints[].clientMethod 生成 IApiClient 接口（仅端点签名），
    /// 与 Kotlin CloudPanApi.g.kt 同源，纳入 --verify：spec 增/改端点后重跑即强制两端签名一致。
    /// 运行时配置方法（SetUploadLimit/SetDownloadLimit）为手工 partial（IApiClient.Config.cs），不属端点契约。
    /// </summary>
    public static string GenerateClientInterface(SpecDocument spec)
    {
        StringBuilder sb = new StringBuilder();
        ClientApiRenderer.AppendGeneratedHeader(sb, spec, "api.endpoints[].clientMethod（C# 客户端接口签名，与 Kotlin CloudPanApi.g.kt 同源）");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Contract;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// API 客户端接口（HTTP 端点签名契约）。由 ApiClientGenerator 从 shared-spec.json → api.endpoints[].clientMethod 生成。");
        sb.AppendLine("/// 与 Kotlin Retrofit 接口（CloudPanApi.g.kt）同源：spec 增/改端点后重跑 CodeGen --verify 强制两端签名一致。");
        sb.AppendLine("/// 仅含端点签名；客户端运行时配置方法（SetUploadLimit/SetDownloadLimit）为手工 partial，见 IApiClient.Config.cs。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public partial interface IApiClient");
        sb.AppendLine("{");
        foreach (var ep in spec.Api.Endpoints)
        {
            if (ep.ClientMethod is null)
            {
                continue;
            }

            foreach (var m in ep.ClientMethod)
            {
                if (!(m.Csharp ?? true))
                {
                    continue;
                }

                sb.AppendLine("    /// <summary>");
                sb.AppendLine($"    /// {EscapeString(ep.Description)}（{ep.Method.ToUpperInvariant()} {ep.Path}）");
                sb.AppendLine("    /// </summary>");
                sb.AppendLine($"    {ClientApiRenderer.CsMethodSignature(m)};");
                sb.AppendLine();
            }
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// 生成 C# ApiClient 方法骨架（CloudPan.Client.Core/Generated/ApiClient.g.cs，partial class）。
    /// 实现 IApiClient 的端点方法：HTTP 方法/路径/参数绑定由 spec 参数段驱动；
    /// spec 标 manual 的复杂方法（上传限速/下载校验/分块编排/健康吞异常）保留手工实现。
    /// </summary>
    public static string GenerateClientClass(SpecDocument spec)
    {
        StringBuilder sb = new StringBuilder();
        ClientApiRenderer.AppendGeneratedHeader(sb, spec, "api.endpoints[].clientMethod（C# 客户端方法骨架：HTTP 方法/路径/参数绑定）");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using System.Net.Http.Json;");
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine("using CloudPan.Contract;");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Client.Core.Services;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// ApiClient 部分类：端点方法骨架。由 ApiClientGenerator 从 shared-spec.json → api.endpoints[].clientMethod 生成。");
        sb.AppendLine("/// 复杂方法（上传限速/下载校验/分块编排/健康吞异常等）在 spec 标 manual 保留手工实现，签名由接口强约束。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public partial class ApiClient");
        sb.AppendLine("{");
        foreach (var ep in spec.Api.Endpoints)
        {
            if (ep.ClientMethod is null)
            {
                continue;
            }

            foreach (var m in ep.ClientMethod)
            {
                if (!(m.Csharp ?? true) || ClientApiRenderer.IsManualFor(m, "csharp"))
                {
                    continue;
                }

                GenerateClassMethod(sb, ep, m);
            }
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void GenerateClassMethod(StringBuilder sb, EndpointDef ep, ClientMethodDef m)
    {
        string route = ToConstantName(ep.Path);
        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// {EscapeString(ep.Description)}（{ep.Method.ToUpperInvariant()} {ep.Path}）。由 shared-spec.json → api.endpoints 生成。");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine($"    public async {ClientApiRenderer.CsMethodSignature(m)}");
        sb.AppendLine("    {");
        ClientApiRenderer.AppendMethodBody(sb, m, route);
        sb.AppendLine("    }");
        sb.AppendLine();
    }
}
