using System.Text;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json 的 api.responses 生成 API 响应包装 record。
/// 替代 ApiClient.cs 中手写的 9 个响应 DTO。
/// </summary>
public static class ApiResponseGenerator
{
    public static string Generate(SpecDocument spec)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine("// 源: shared-spec.json → api.responses")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine();
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Shared;");
        sb.AppendLine();

        var responses = spec.Api.Responses;
        if (responses == null || responses.Count == 0)
        {
            sb.AppendLine("// api.responses 段为空，无响应类型生成。");
            return sb.ToString();
        }

        foreach (var (name, def) in responses)
        {
            sb.AppendLine($"/// <summary>");
            sb.AppendLine($"/// {def.Description}");
            sb.AppendLine($"/// </summary>");

            switch (name)
            {
                case "FileTreeResponse":
                    GenerateFileTreeResponse(sb);
                    break;
                case "UploadResponse":
                    GenerateUploadResponse(sb);
                    break;
                case "ChunkUploadResponse":
                    GenerateChunkUploadResponse(sb);
                    break;
                default:
                    sb.AppendLine($"// TODO: 未实现的响应类型生成: {name}");
                    sb.AppendLine();
                    break;
            }
        }

        return sb.ToString();
    }

    private static void GenerateFileTreeResponse(StringBuilder sb)
    {
        sb.AppendLine("public record FileTreeResponse(");
        sb.AppendLine("    [property: JsonPropertyName(\"data\")]");
        sb.AppendLine("    FileEntryDto[] Data,");
        sb.AppendLine("    [property: JsonPropertyName(\"nextCursor\")]");
        sb.AppendLine("    string? NextCursor,");
        sb.AppendLine("    [property: JsonPropertyName(\"hasMore\")]");
        sb.AppendLine("    bool HasMore,");
        sb.AppendLine("    [property: JsonPropertyName(\"maxVersion\")]");
        sb.AppendLine("    int MaxVersion");
        sb.AppendLine(");");
        sb.AppendLine();
    }

    private static void GenerateUploadResponse(StringBuilder sb)
    {
        sb.AppendLine("public record UploadResponse(");
        sb.AppendLine("    [property: JsonPropertyName(\"ok\")]");
        sb.AppendLine("    bool Ok,");
        sb.AppendLine("    [property: JsonPropertyName(\"data\")]");
        sb.AppendLine("    UploadResponseData Data");
        sb.AppendLine(");");
        sb.AppendLine();
        sb.AppendLine("/// <summary>上传响应中的 data 字段。</summary>");
        sb.AppendLine("public record UploadResponseData(");
        sb.AppendLine("    [property: JsonPropertyName(\"path\")]");
        sb.AppendLine("    string Path,");
        sb.AppendLine("    [property: JsonPropertyName(\"version\")]");
        sb.AppendLine("    int Version,");
        sb.AppendLine("    [property: JsonPropertyName(\"hash\")]");
        sb.AppendLine("    string Hash,");
        sb.AppendLine("    [property: JsonPropertyName(\"size\")]");
        sb.AppendLine("    long Size,");
        sb.AppendLine("    [property: JsonPropertyName(\"conflictResolved\")]");
        sb.AppendLine("    bool? ConflictResolved = null");
        sb.AppendLine(");");
        sb.AppendLine();
    }

    private static void GenerateChunkUploadResponse(StringBuilder sb)
    {
        sb.AppendLine("public record ChunkUploadResponse(");
        sb.AppendLine("    [property: JsonPropertyName(\"ok\")]");
        sb.AppendLine("    bool Ok,");
        sb.AppendLine("    [property: JsonPropertyName(\"chunkIndex\")]");
        sb.AppendLine("    int ChunkIndex,");
        sb.AppendLine("    [property: JsonPropertyName(\"received\")]");
        sb.AppendLine("    int Received,");
        sb.AppendLine("    [property: JsonPropertyName(\"total\")]");
        sb.AppendLine("    int Total,");
        sb.AppendLine("    [property: JsonPropertyName(\"done\")]");
        sb.AppendLine("    bool Done");
        sb.AppendLine(");");
        sb.AppendLine();
    }
}
