using System.Text;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json 的 api.responses 生成 API 响应包装 record。
/// 替代 ApiClient.cs 中手写的 API 响应 DTO。
///
/// 响应类型字段格式（api.responses → {name}.fields）：
///   "data: FileEntryDto[]"   → 数组（引用 DTO/嵌套响应类型）
///   "nextCursor: string?"    → 可空引用类型
///   "version: int"           → 基础类型
/// 字段名即 JSON 属性名（camelCase），与服务端匿名对象返回形状一一对应。
/// </summary>
public static class ApiResponseGenerator
{
    public static string Generate(SpecDocument spec)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine("// 源: shared-spec.json → api.responses")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine();
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Shared;");
        sb.AppendLine();

        var responses = spec.Api.Responses;
        if (responses == null || responses.Count == 0)
        {
            sb.AppendLine("// api.responses 段为空，无响应类型生成。");
            return sb.ToString();
        }

        foreach (var (name, def) in responses)
        {
            GenerateRecord(sb, name, def);
        }

        return sb.ToString();
    }

    private static void GenerateRecord(StringBuilder sb, string name, ApiResponseDef def)
    {
        List<(string JsonName, string PropName, string CsType)> fields = ParseFields(def.Fields);

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {def.Description}");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public record {name}(");

        for (int i = 0; i < fields.Count; i++)
        {
            var (jsonName, propName, csType) = fields[i];
            string comma = i < fields.Count - 1 ? "," : "";
            sb.AppendLine($"    [property: JsonPropertyName(\"{jsonName}\")]");
            sb.AppendLine($"    {csType} {propName}{comma}");
        }

        sb.AppendLine(");");
        sb.AppendLine();
    }

    /// <summary>
    /// 解析字段描述 "propName: typeExpr"，返回（JSON 属性名，C# 属性名，C# 类型）。
    /// 字段名为 camelCase，同时作 JSON 属性名；C# 属性名转 PascalCase（符合 .NET 命名规范）。
    /// </summary>
    private static List<(string JsonName, string PropName, string CsType)> ParseFields(List<string> fields)
    {
        List<(string, string, string)> result = new List<(string, string, string)>();
        foreach (string field in fields)
        {
            int colon = field.IndexOf(':');
            if (colon < 0)
            {
                continue;
            }

            string fieldName = field[..colon].Trim();
            string typeExpr = field[(colon + 1)..].Trim();
            result.Add((fieldName, ToPascalCase(fieldName), MapToCSharp(typeExpr)));
        }

        return result;
    }

    /// <summary>camelCase 字段名 → PascalCase C# 属性名（如 nextCursor → NextCursor）。</summary>
    private static string ToPascalCase(string camelName)
    {
        if (string.IsNullOrEmpty(camelName))
        {
            return camelName;
        }

        return char.ToUpperInvariant(camelName[0]) + camelName[1..];
    }

    /// <summary>
    /// 类型表达式 → C# 类型。支持基础类型映射、可空后缀 "?"、数组后缀 "[]"；
    /// 其余视为引用类型（DTO 或嵌套响应 record），直接保留原名。
    /// </summary>
    private static string MapToCSharp(string typeExpr)
    {
        string t = typeExpr;

        bool nullable = t.EndsWith("?");
        if (nullable)
        {
            t = t[..^1];
        }

        bool array = t.EndsWith("[]");
        if (array)
        {
            t = t[..^2];
        }

        string baseType = t switch
        {
            "string" => "string",
            "int" => "int",
            "long" => "long",
            "bool" => "bool",
            _ => t // 引用类型（FileEntryDto / UploadData / ChunkUploadData / ChunkStatusData 等）
        };

        string csType = baseType + (array ? "[]" : "") + (nullable ? "?" : "");
        return csType;
    }
}
