using System.Text;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json 的 api.endpoints 段生成 ASP.NET Core Controller 骨架。
/// </summary>
public static class ControllerStubGenerator
{
    public static string Generate(SpecDocument spec)
    {
        // 按第一段路径分组：/api/files/* → FilesController
        var groups = spec.Api.Endpoints
            .Where(e => e.Path.StartsWith("/api/"))
            .GroupBy(e => GetControllerGroup(e.Path))
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine("// 源: shared-spec.json → api.endpoints")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine("//")
          .AppendLine("// ⚠️ 仅生成路由骨架。业务逻辑需手动实现。")
          .AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Server.Controllers;");
        sb.AppendLine();

        foreach (var group in groups)
        {
            var controllerName = group.Key;
            var endpoints = group.ToList();

            sb.AppendLine($"/// <summary>");
            sb.AppendLine($"/// {controllerName} 相关 API");
            sb.AppendLine($"/// </summary>");
            sb.AppendLine($"[ApiController]");
            sb.AppendLine($"[Route(\"api/{controllerName.ToLower()}\")]");
            sb.AppendLine($"public class {controllerName}Controller : ControllerBase");
            sb.AppendLine("{");

            foreach (var ep in endpoints)
            {
                var actionName = GetActionName(ep);
                var httpMethod = GetHttpMethodAttribute(ep.Method);
                var route = ep.Path.Replace($"/api/{controllerName.ToLower()}", "").Trim('/');
                var routeAttr = string.IsNullOrEmpty(route) ? "" : $"(\"{route}\")";

                sb.AppendLine($"    /// <summary>{ep.Description}</summary>");
                sb.AppendLine($"    [{httpMethod}{routeAttr}]");

                // 生成方法签名
                var returnType = "Task<IActionResult>";
                var parameters = GetDefaultParameters(ep);

                sb.AppendLine($"    public async {returnType} {actionName}({parameters})");
                sb.AppendLine($"    {{");
                sb.AppendLine($"        // TODO: 实现 {ep.Description}");
                sb.AppendLine($"        throw new NotImplementedException(\"{ep.Description}\");");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        // /share/* 路径单独生成（无需 Token 认证）
        var shareEndpoints = spec.Api.Endpoints
            .Where(e => e.Path.StartsWith("/share/"))
            .ToList();

        if (shareEndpoints.Count > 0)
        {
            sb.AppendLine($"/// <summary>");
            sb.AppendLine($"/// 分享链接访问（无需 Token 认证）");
            sb.AppendLine($"/// </summary>");
            sb.AppendLine($"[ApiController]");
            sb.AppendLine($"public class ShareController : ControllerBase");
            sb.AppendLine("{");

            foreach (var ep in shareEndpoints)
            {
                var actionName = GetActionName(ep);
                var httpMethod = GetHttpMethodAttribute(ep.Method);
                var routeTemplate = ep.Path.Replace("/share/", "");

                sb.AppendLine($"    /// <summary>{ep.Description}</summary>");
                sb.AppendLine($"    [{httpMethod}(\"{routeTemplate}\")]");
                sb.AppendLine($"    public async Task<IActionResult> {actionName}(string shareId)");
                sb.AppendLine($"    {{");
                sb.AppendLine($"        // TODO: 实现 {ep.Description}");
                sb.AppendLine($"        throw new NotImplementedException(\"{ep.Description}\");");
                sb.AppendLine($"    }}");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    private static string GetControllerGroup(string path)
    {
        // /api/files/tree → Files
        // /api/files/upload → Files
        // /api/versions → Versions
        // /api/devices → Devices
        var parts = path.Split('/');
        if (parts.Length >= 3)
            return char.ToUpper(parts[2][0]) + parts[2][1..];
        return "Home";
    }

    private static string GetActionName(EndpointDef ep)
    {
        // /api/files/upload → Upload, /api/files/tree → GetTree
        var methodPrefix = ep.Method == "GET" ? "Get" : "";
        var path = ep.Path.Split('?')[0];
        var parts = path.Split('/');
        // 跳过 /api/{controller} 前缀，只取动作部分
        var actionParts = parts.Skip(3); // /api/files/upload → ["upload"]
        if (actionParts.Count() == 0)
            actionParts = parts.Skip(2); // 没有子路径的情况

        var name = string.Join("", actionParts.Select((p, i) =>
            p.Contains('{') ? "ById" : char.ToUpper(p[0]) + p[1..]));
        return $"{methodPrefix}{name}";
    }

    private static string GetHttpMethodAttribute(string method)
    {
        return method switch
        {
            "GET" => "HttpGet",
            "POST" => "HttpPost",
            "PUT" => "HttpPut",
            "DELETE" => "HttpDelete",
            "PATCH" => "HttpPatch",
            _ => "HttpGet"
        };
    }

    private static string GetDefaultParameters(EndpointDef ep)
    {
        // 简单推断常见参数
        var parts = ep.Path.Split('/');
        var hasPathParam = parts.Any(p => p.Contains('{'));

        if (ep.Path.Contains("{shareId}"))
            return "string shareId";

        // 文件下载 → path query param
        if (ep.Path == "/api/files/download")
            return "[FromQuery] string path, [FromQuery] int? version = null";

        if (ep.Path == "/api/files/tree")
            return "[FromQuery] int? sinceVersion = null, [FromQuery] string? path = null, [FromQuery] int limit = 5000, [FromQuery] string? cursor = null";

        if (ep.Path == "/api/versions")
            return "[FromQuery] string path";

        if (ep.Path == "/api/files/search")
            return "[FromQuery] string q, [FromQuery] int limit = 50";

        if (ep.Path == "/api/thumbnails")
            return "[FromQuery] string path, [FromQuery] int size = 200";

        if (ep.Path.Contains("chunk/status"))
            return "[FromQuery] string path, [FromQuery] string fileHash, [FromQuery] int totalChunks";

        // 默认：json body
        if (ep.Method != "GET")
            return "[FromBody] object request";

        return "";
    }
}
