using System.Text;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json 的 entities 段生成 API DTO record。
/// 仅处理有 apiMapping 的实体（即对外暴露的类型）。
/// </summary>
public static class DtoGenerator
{
    public static string Generate(SpecDocument spec)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine("// 源: shared-spec.json → entities → apiMapping")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine();
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Contract;");
        sb.AppendLine();

        foreach (var (entityName, entity) in spec.Entities)
        {
            if (entity.ApiMapping == null || entity.ApiMapping.Count == 0)
            {
                continue;
            }

            // 收集要暴露的字段
            List<(FieldDef Field, string JsonName)> mappedFields = new List<(FieldDef Field, string JsonName)>();
            foreach (var field in entity.Fields)
            {
                if (entity.ApiMapping.TryGetValue(field.Name, out string? jsonName))
                {
                    mappedFields.Add((field, jsonName));
                }
            }

            if (mappedFields.Count == 0)
            {
                continue;
            }

            string dtoName = $"{entityName}Dto";

            sb.AppendLine($"/// <summary>");
            sb.AppendLine($"/// {entity.Description}");
            sb.AppendLine($"/// </summary>");
            sb.AppendLine($"public record {dtoName}(");

            for (int i = 0; i < mappedFields.Count; i++)
            {
                var (field, jsonName) = mappedFields[i];
                string comma = i < mappedFields.Count - 1 ? "," : "";
                string csType = TypeMapper.MapToCSharp(field);
                string nullable = field.Nullable ? "?" : "";

                sb.AppendLine($"    [property: JsonPropertyName(\"{jsonName}\")]");
                sb.AppendLine($"    {csType}{nullable} {field.Name}{comma}");
            }

            sb.AppendLine(");");
            sb.AppendLine();
        }

        return sb.ToString();
    }

}
