using System.Text;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json 的 entities 段生成 EF Core 实体类。
/// 仅处理服务端实体（客户端本地表跳过）。
/// 索引从各实体的 indexes 字段生成，非硬编码。
/// </summary>
public static class EntityGenerator
{
    private static readonly HashSet<string> ClientOnlyTables = new()
    {
        "SyncQueue", "RemoteSnapshot", "SyncCursor", "BackupLog", "OfflineCache"
    };

    public static string Generate(SpecDocument spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine("// 源: shared-spec.json → entities")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine();
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Server.Models;");
        sb.AppendLine();

        foreach (var (entityName, entity) in spec.Entities)
        {
            if (ClientOnlyTables.Contains(entityName))
                continue;

            var tableName = entity.Table;

            sb.AppendLine($"/// <summary>");
            sb.AppendLine($"/// {entity.Description}");
            sb.AppendLine($"/// </summary>");
            sb.AppendLine($"[Table(\"{tableName}\")]");

            // 从 spec 的 indexes 字段生成实际索引
            if (entity.Indexes != null && entity.Indexes.Count > 0)
            {
                foreach (var idxSql in entity.Indexes)
                {
                    // 格式: "idx_xxx ON TableName(Col1, Col2 DESC)"
                    var attr = ParseIndexAttribute(idxSql);
                    if (attr != null)
                        sb.AppendLine(attr);
                }
            }

            sb.AppendLine($"public class {entityName}");
            sb.AppendLine("{");

            foreach (var field in entity.Fields)
            {
                var csType = MapToCSharpType(field);
                var nullable = field.Nullable && csType != "string" ? "?" : "";
                var isPk = field.Role.Contains("PK");
                var isAutoIncrement = field.Role.Contains("AUTOINCREMENT");

                sb.AppendLine($"    /// <summary>{field.Description ?? field.Name}</summary>");

                if (isPk)
                {
                    sb.AppendLine($"    [Key]");
                    if (isAutoIncrement)
                        sb.AppendLine($"    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]");
                }

                if (!field.Nullable && csType == "string")
                    sb.AppendLine($"    [Required]");

                var defaultValue = GetDefaultValue(field);
                var defaultExpr = defaultValue != null ? $" = {defaultValue};" : "";

                sb.AppendLine($"    public {csType}{nullable} {field.Name} {{ get; set; }}{defaultExpr}");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    /// <summary>
    /// 将索引 SQL 片段转为 C# [Index] 属性。
    /// 输入: "idx_fileentry_state ON FileEntry(State)"
    /// 输出: "[Index(nameof(State))]"
    /// </summary>
    private static string? ParseIndexAttribute(string indexSql)
    {
        // 提取列名部分
        var onIdx = indexSql.IndexOf(" ON ", StringComparison.OrdinalIgnoreCase);
        if (onIdx < 0) return null;

        var afterOn = indexSql[(onIdx + 4)..]; // "FileEntry(State)" or "FileEntry(FilePath, Version DESC)"
        var parenStart = afterOn.IndexOf('(');
        var parenEnd = afterOn.LastIndexOf(')');
        if (parenStart < 0 || parenEnd < 0) return null;

        var columnsPart = afterOn[(parenStart + 1)..parenEnd]; // "State" or "FilePath, Version DESC"
        var columns = columnsPart.Split(',')
            .Select(c => c.Trim().Split(' ')[0]) // 去掉 DESC/ASC
            .Select(c => $"nameof({c})");

        var isUnique = indexSql.Contains("UNIQUE", StringComparison.OrdinalIgnoreCase);

        // 单列简单索引
        if (columns.Count() == 1 && !isUnique)
            return $"    [Index({string.Join(", ", columns)})]";

        // 多列或唯一索引
        var uniqueFlag = isUnique ? "IsUnique = true, " : "";
        return $"    [Index({string.Join(", ", columns)}, {uniqueFlag}Name = \"{indexSql.Split(' ')[0]}\")]";
    }

    private static string MapToCSharpType(FieldDef field)
    {
        return field.Type switch
        {
            "TEXT" => "string",
            "INTEGER" => "int",
            "REAL" => "double",
            "BLOB" => "byte[]",
            _ => "string"
        };
    }

    private static string? GetDefaultValue(FieldDef field)
    {
        if (field.Description?.Contains("默认 0") == true) return "0";
        if (field.Description?.Contains("默认 1") == true) return "1";
        return null;
    }
}
