using System.Text;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json 的 entities 段生成 EF Core 实体类。
/// 仅处理服务端实体（客户端本地表跳过）。
/// 索引从各实体的 indexes 字段生成，非硬编码。
/// </summary>
public static class EntityGenerator
{
    private static readonly HashSet<string> ClientOnlyTables = new()
    {
        "SyncQueue", "RemoteSnapshot", "SyncCursor", "BackupLog", "OfflineCache"
    };

    public static string Generate(SpecDocument spec)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine("// 源: shared-spec.json → entities")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine();
        sb.AppendLine("#pragma warning disable CS8618 // EF Core 实体由 DbContext 填充，非 null 字段无需初始化");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Server.Models;");
        sb.AppendLine();

        foreach (var (entityName, entity) in spec.Entities)
        {
            if (ClientOnlyTables.Contains(entityName))
                continue;

            var tableName = entity.Table;

            sb.AppendLine($"/// <summary>");
            sb.AppendLine($"/// {entity.Description}");
            sb.AppendLine($"/// </summary>");
            sb.AppendLine($"[Table(\"{tableName}\")]");

            // 从 spec 的 indexes 字段生成实际索引
            if (entity.Indexes != null && entity.Indexes.Count > 0)
            {
                foreach (var idxSql in entity.Indexes)
                {
                    // 格式: "idx_xxx ON TableName(Col1, Col2 DESC)"
                    var attr = ParseIndexAttribute(idxSql);
                    if (attr != null)
                        sb.AppendLine(attr);
                }
            }

            sb.AppendLine($"public class {entityName}");
            sb.AppendLine("{");

            foreach (var field in entity.Fields)
            {
                var csType = TypeMapper.MapToCSharp(field);
                var nullable = field.Nullable ? "?" : "";
                var isPk = field.Role.Contains("PK");
                var isAutoIncrement = field.Role.Contains("AUTOINCREMENT");
                var isFk = field.Role.Contains("FK");

                sb.AppendLine($"    /// <summary>{field.Description ?? field.Name}</summary>");

                if (isPk)
                {
                    sb.AppendLine($"    [Key]");
                    if (isAutoIncrement)
                        sb.AppendLine($"    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]");
                }

                if (isFk)
                {
                    // 从 FK→Entity(Col) 中提取目标类型
                    var fkTarget = ParseForeignKeyType(field.Role);
                    if (fkTarget != null)
                        sb.AppendLine($"    [ForeignKey(nameof({fkTarget}))]");
                }

                if (!field.Nullable && csType == "string")
                    sb.AppendLine($"    [Required]");

                var defaultValue = GetDefaultValue(field);
                var defaultExpr = defaultValue != null ? $" = {defaultValue};" : "";

                sb.AppendLine($"    public {csType}{nullable} {field.Name} {{ get; set; }}{defaultExpr}");
                sb.AppendLine();
            }

            sb.AppendLine("}");
            sb.AppendLine();

            // 为 AppConfig 生成预定义键常量
            if (entityName == "AppConfig" && entity.PredefinedKeys != null && entity.PredefinedKeys.Count > 0)
            {
                sb.AppendLine($"/// <summary>");
                sb.AppendLine($"/// AppConfig 预定义键名常量。");
                sb.AppendLine($"/// </summary>");
                sb.AppendLine($"public static class AppConfigKeys");
                sb.AppendLine("{");
                foreach (var (key, description) in entity.PredefinedKeys)
                {
                    sb.AppendLine($"    /// <summary>{description}</summary>");
                    sb.AppendLine($"    public const string {ToPascalCase(key)} = \"{key}\";");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    private static string ToPascalCase(string key)
    {
        return string.Concat(key.Split('_')
            .Select(p => p.Length > 0 ? char.ToUpper(p[0]) + p[1..] : ""));
    }

    /// <summary>
    /// 将索引 SQL 片段转为 C# [Index] 属性。
    /// 输入: "idx_fileentry_state ON FileEntry(State)"
    /// 输出: "[Index(nameof(State))]"
    /// </summary>
    private static string? ParseIndexAttribute(string indexSql)
    {
        // 提取列名部分
        var onIdx = indexSql.IndexOf(" ON ", StringComparison.OrdinalIgnoreCase);
        if (onIdx < 0) return null;

        var afterOn = indexSql[(onIdx + 4)..]; // "FileEntry(State)" or "FileEntry(FilePath, Version DESC)"
        var parenStart = afterOn.IndexOf('(');
        var parenEnd = afterOn.LastIndexOf(')');
        if (parenStart < 0 || parenEnd < 0) return null;

        var columnsPart = afterOn[(parenStart + 1)..parenEnd]; // "State" or "FilePath, Version DESC"
        var columns = columnsPart.Split(',')
            .Select(c => c.Trim().Split(' ')[0]) // 去掉 DESC/ASC
            .Select(c => $"nameof({c})");

        var isUnique = indexSql.Contains("UNIQUE", StringComparison.OrdinalIgnoreCase);

        // 单列简单索引
        if (columns.Count() == 1 && !isUnique)
            return $"    [Index({string.Join(", ", columns)})]";

        // 多列或唯一索引
        var uniqueFlag = isUnique ? "IsUnique = true, " : "";
        return $"    [Index({string.Join(", ", columns)}, {uniqueFlag}Name = \"{indexSql.Split(' ')[0]}\")]";
    }

    /// <summary>
    /// 从 FK→Entity(Col) 格式中提取目标实体类型名。
    /// </summary>
    private static string? ParseForeignKeyType(string role)
    {
        var fkMarker = "FK→";
        var idx = role.IndexOf(fkMarker);
        if (idx < 0) return null;
        var start = idx + fkMarker.Length;
        var parenIdx = role.IndexOf('(', start);
        if (parenIdx < 0) return role[start..].Trim();
        return role[start..parenIdx].Trim();
    }

    private static string? GetDefaultValue(FieldDef field)
    {
        if (field.Description?.Contains("默认 0") == true) return "0";
        if (field.Description?.Contains("默认 1") == true) return "1";
        return null;
    }
}
