using System.Text;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json 的 entities 段生成 EF Core 实体类。
/// 服务端实体（Generate）与客户端本地实体（GenerateClient）同源由 spec 生成（规则 0 契约驱动）。
/// 索引从各实体的 indexes 字段生成，非硬编码；DESC/ASC 排序信息保留（IsDescending）。
/// </summary>
public static class EntityGenerator
{
    /// <summary>非服务端表：客户端本地表 + Android 专用表 + API 请求 DTO（非持久化，仅 apiMapping 驱动 DtoGenerator），服务端生成跳过。</summary>
    private static readonly HashSet<string> ServerExcludedTables = new()
    {
        "SyncQueue", "RemoteSnapshot", "SyncCursor", "BackupLog", "OfflineCache",
        "DeleteRequest", "MoveRequest", "MkdirRequest", "CreateShareRequest", "RestoreTrashRequest", "RestoreRequest"
    };

    /// <summary>C# 客户端本地表：从 spec 生成到 CloudPan.Client.Core.Models（客户端 EF 实体，T-062）。</summary>
    private static readonly HashSet<string> ClientCsTables = new()
    {
        "SyncQueue", "RemoteSnapshot", "SyncCursor"
    };

    public static string Generate(SpecDocument spec)
    {
        StringBuilder sb = new StringBuilder();
        WriteHeader(sb, spec, "shared-spec.json → entities");
        sb.AppendLine("namespace CloudPan.Infrastructure.Models;");
        sb.AppendLine();

        foreach (var (entityName, entity) in spec.Entities)
        {
            if (ServerExcludedTables.Contains(entityName))
            {
                continue;
            }

            WriteEntity(sb, entityName, entity);

            // 为 AppConfig 生成预定义键常量
            if (entityName == "AppConfig" && entity.PredefinedKeys != null && entity.PredefinedKeys.Count > 0)
            {
                sb.AppendLine($"/// <summary>");
                sb.AppendLine($"/// AppConfig 预定义键名常量。");
                sb.AppendLine($"/// </summary>");
                sb.AppendLine($"public static class AppConfigKeys");
                sb.AppendLine("{");
                foreach (var (key, description) in entity.PredefinedKeys)
                {
                    sb.AppendLine($"    /// <summary>{description}</summary>");
                    sb.AppendLine($"    public const string {Naming.ToPascalCase(key)} = \"{key}\";");
                }
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// 客户端 EF 实体输出（CloudPan.Infrastructure/Generated/ClientEntities.g.cs，T-068 随持久化迁入基础设施层）。
    /// 与服务端实体同命名空间 CloudPan.Infrastructure.Models，客户端 DbContext 直接引用生成类型。
    /// </summary>
    public static string GenerateClient(SpecDocument spec)
    {
        StringBuilder sb = new StringBuilder();
        WriteHeader(sb, spec, "shared-spec.json → entities（客户端本地表）");
        sb.AppendLine("namespace CloudPan.Infrastructure.Models;");
        sb.AppendLine();

        foreach (var (entityName, entity) in spec.Entities)
        {
            if (ClientCsTables.Contains(entityName))
            {
                WriteEntity(sb, entityName, entity);
            }
        }

        return sb.ToString();
    }

    private static void WriteHeader(StringBuilder sb, SpecDocument spec, string sourceLine)
    {
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine($"// 源: {sourceLine}")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine();
        sb.AppendLine("#pragma warning disable CS8618 // EF Core 实体由 DbContext 填充，非 null 字段无需初始化");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        sb.AppendLine("using System.ComponentModel.DataAnnotations.Schema;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
    }

    private static void WriteEntity(StringBuilder sb, string entityName, EntityDef entity)
    {
        string tableName = entity.Table;

        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {entity.Description}");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"[Table(\"{tableName}\")]");

        // 从 spec 的 indexes 字段生成实际索引
        if (entity.Indexes != null && entity.Indexes.Count > 0)
        {
            foreach (string idxSql in entity.Indexes)
            {
                // 格式: "idx_xxx ON TableName(Col1, Col2 DESC)"
                string? attr = ParseIndexAttribute(idxSql);
                if (attr != null)
                {
                    sb.AppendLine(attr);
                }
            }
        }

        sb.AppendLine($"public class {entityName}");
        sb.AppendLine("{");

        foreach (var field in entity.Fields)
        {
            string csType = TypeMapper.MapToCSharp(field);
            string nullable = field.Nullable ? "?" : "";
            // Role 可能为空（spec 字段未声明 role），空安全判断
            bool isPk = field.Role?.Contains("PK") == true;
            bool isAutoIncrement = field.Role?.Contains("AUTOINCREMENT") == true;
            bool isFk = field.Role?.Contains("FK") == true;

            sb.AppendLine($"    /// <summary>{field.Description ?? field.Name}</summary>");

            if (isPk)
            {
                sb.AppendLine($"    [Key]");
                if (isAutoIncrement)
                {
                    sb.AppendLine($"    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]");
                }
            }

            if (isFk)
            {
                // 从 FK→Entity(Col) 中提取目标类型
                string? fkTarget = ParseForeignKeyType(field.Role!);
                if (fkTarget != null)
                {
                    sb.AppendLine($"    [ForeignKey(nameof({fkTarget}))]");
                }
            }

            if (!field.Nullable && csType == "string")
            {
                sb.AppendLine($"    [Required]");
            }

            string? defaultValue = GetDefaultValue(field);
            string defaultExpr = defaultValue != null ? $" = {defaultValue};" : "";

            sb.AppendLine($"    public {csType}{nullable} {field.Name} {{ get; set; }}{defaultExpr}");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    /// <summary>
    /// 将索引 SQL 片段转为 C# [Index] 属性。
    /// 输入: "idx_fileentry_state ON FileEntry(State)"
    /// 输出: "[Index(nameof(State))]"
    /// 输入: "idx_queue_sort ON SyncQueue(Priority DESC, CreatedAt ASC)"
    /// 输出: "[Index(nameof(Priority), nameof(CreatedAt), IsDescending = new[] { true, false }, Name = "idx_queue_sort")]"
    /// </summary>
    private static string? ParseIndexAttribute(string indexSql)
    {
        // 提取列名部分
        int onIdx = indexSql.IndexOf(" ON ", StringComparison.OrdinalIgnoreCase);
        if (onIdx < 0)
        {
            return null;
        }

        string afterOn = indexSql[(onIdx + 4)..]; // "FileEntry(State)" or "FileEntry(FilePath, Version DESC)"
        int parenStart = afterOn.IndexOf('(');
        int parenEnd = afterOn.LastIndexOf(')');
        if (parenStart < 0 || parenEnd < 0)
        {
            return null;
        }

        string columnsPart = afterOn[(parenStart + 1)..parenEnd]; // "State" or "Priority DESC, CreatedAt ASC"
        var columnTokens = columnsPart.Split(',')
            .Select(c => c.Trim())
            .ToList();

        var columnNames = columnTokens
            .Select(c => c.Split(' ')[0]) // 去掉 DESC/ASC
            .Select(c => $"nameof({c})")
            .ToList();

        bool hasDescending = columnTokens.Any(c => c.Contains("DESC", StringComparison.OrdinalIgnoreCase));
        bool isUnique = indexSql.Contains("UNIQUE", StringComparison.OrdinalIgnoreCase);

        // 单列简单索引
        if (columnNames.Count == 1 && !isUnique && !hasDescending)
        {
            return $"    [Index({string.Join(", ", columnNames)})]";
        }

        // 多列 / 唯一 / 含排序方向的索引：保留 IsDescending（DESC 置 true）与 spec 索引名
        string descendingPart = "";
        if (hasDescending)
        {
            var descendingFlags = columnTokens.Select(c =>
                c.Contains("DESC", StringComparison.OrdinalIgnoreCase) ? "true" : "false");
            descendingPart = $"IsDescending = new[] {{ {string.Join(", ", descendingFlags)} }}, ";
        }

        string uniqueFlag = isUnique ? "IsUnique = true, " : "";
        return $"    [Index({string.Join(", ", columnNames)}, {descendingPart}{uniqueFlag}Name = \"{indexSql.Split(' ')[0]}\")]";
    }

    /// <summary>
    /// 从 FK→Entity(Col) 格式中提取目标实体类型名。
    /// </summary>
    private static string? ParseForeignKeyType(string role)
    {
        string fkMarker = "FK→";
        int idx = role.IndexOf(fkMarker);
        if (idx < 0)
        {
            return null;
        }

        int start = idx + fkMarker.Length;
        int parenIdx = role.IndexOf('(', start);
        if (parenIdx < 0)
        {
            return role[start..].Trim();
        }

        return role[start..parenIdx].Trim();
    }

    private static string? GetDefaultValue(FieldDef field)
    {
        // spec 显式声明的 C# 默认值表达式优先（如 SyncQueue.CreatedAt = DateTime.UtcNow.ToString("O")）
        if (!string.IsNullOrEmpty(field.Default))
        {
            return field.Default;
        }

        if (field.Description?.Contains("默认 0") == true)
        {
            return "0";
        }

        if (field.Description?.Contains("默认 1") == true)
        {
            return "1";
        }

        return null;
    }
}
