using System.Text;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json 的 enums 段生成 C# 类型。
/// 支持三种格式：
///   - 数值枚举：FileState, FileType, SyncOperation, QueuePriority, LogResult, BackupStatus
///   - 字符串常量类：WebSocketEvent
///   - 错误码记录类：HttpErrorCode（含 http code retry 元数据）
/// </summary>
public static class EnumGenerator
{
    public static string Generate(SpecDocument spec)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine("// 源: shared-spec.json → enums")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Shared;");
        sb.AppendLine();

        foreach (var (enumName, enumDef) in spec.Enums)
        {
            // HttpErrorCode → 特殊处理，生成带元数据的记录类
            var httpCodes = enumDef.GetHttpErrorCodeValues();
            if (httpCodes.Count > 0)
            {
                GenerateHttpErrorCodes(sb, enumName, enumDef.Description, httpCodes);
                continue;
            }

            var values = enumDef.GetValues();
            if (values.Count == 0)
            {
                continue;
            }

            // 字符串数组（无显式数值）→ 生成 static class + const string
            if (values.All(v => v.Value == null))
            {
                GenerateStringConstants(sb, enumName, enumDef.Description, values);
                continue;
            }

            // 标准数值枚举
            GenerateNumericEnum(sb, enumName, enumDef.Description, values);
        }

        return sb.ToString();
    }

    private static void GenerateNumericEnum(StringBuilder sb, string name, string description, List<EnumValue> values)
    {
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {description}");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public enum {name}");
        sb.AppendLine("{");

        // 检测是否存在空洞（如 FileState 跳过 6）
        for (int i = 0; i < values.Count; i++)
        {
            var v = values[i];
            int val = v.Value ?? i;
            string comma = i < values.Count - 1 ? "," : "";

            if (!string.IsNullOrEmpty(v.Note))
            {
                sb.AppendLine($"    /// <summary>{v.Note}</summary>");
            }

            string scopeSuffix = v.Scope == "client-only" ? " // 仅客户端" : "";
            sb.AppendLine($"    {v.Name} = {val}{comma}{scopeSuffix}");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateStringConstants(StringBuilder sb, string name, string description, List<EnumValue> values)
    {
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {description}");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public static class {name}");
        sb.AppendLine("{");

        foreach (var v in values)
        {
            sb.AppendLine($"    public const string {Naming.ToPascalCase(v.Name!)} = \"{v.Name}\";");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateHttpErrorCodes(StringBuilder sb, string name, string description, List<HttpErrorCodeValue> codes)
    {
        // 先定义 ErrorCode 记录
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// HTTP 错误码元数据。");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public record ErrorCode(int HttpStatus, string Code, bool Retry, string? Note = null);");
        sb.AppendLine();

        // 再定义静态常量类
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// {description}");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public static class {name}");
        sb.AppendLine("{");

        foreach (var c in codes)
        {
            string fieldName = c.Code; // BAD_REQUEST, UNAUTHORIZED, etc.
            string note = c.Note != null ? $", Note: \"{c.Note}\"" : "";
            sb.AppendLine($"    /// <summary>HTTP {c.Http} — {c.Code}{(c.Retry ? "（可重试）" : "")}</summary>");
            sb.AppendLine($"    public static readonly ErrorCode {fieldName} = new({c.Http}, \"{c.Code}\", {(c.Retry ? "true" : "false")}{note});");
        }

        sb.AppendLine("}");
        sb.AppendLine();
    }

}
