using System.Text;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json 的 api.errorResponse 生成统一错误响应 record。
/// 替代所有控制器/中间件中的内联匿名对象和手写 JSON 错误体。
/// </summary>
public static class ErrorResponseGenerator
{
    public static string Generate(SpecDocument spec)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine("// 源: shared-spec.json → api.errorResponse")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine();
        sb.AppendLine("using System.Text.Json.Serialization;");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Shared;");
        sb.AppendLine();

        var errorDef = spec.Api.ErrorResponse;
        string desc = errorDef?.Description ?? "统一 API 错误响应体";

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// {desc}");
        sb.AppendLine("/// 四个字段：code (错误码)、message (开发者消息)、friendlyMessage (用户消息)、detail (可选调试详情)");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public record ErrorResponse(");
        sb.AppendLine("    [property: JsonPropertyName(\"code\")]");
        sb.AppendLine("    string Code,");
        sb.AppendLine("    [property: JsonPropertyName(\"message\")]");
        sb.AppendLine("    string Message,");
        sb.AppendLine("    [property: JsonPropertyName(\"friendlyMessage\")]");
        sb.AppendLine("    string FriendlyMessage,");
        sb.AppendLine("    [property: JsonPropertyName(\"detail\")]");
        sb.AppendLine("    [property: JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]");
        sb.AppendLine("    string? Detail = null");
        sb.AppendLine(")");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>将错误响应包装为 { error: ErrorResponse } 的 JSON 兼容形状。</summary>");
        sb.AppendLine("    public object ToApiBody() => new { error = this };");
        sb.AppendLine("}");
        sb.AppendLine();

        return sb.ToString();
    }
}
