using System.Text;
using System.Text.Json;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json 生成 ContractManifest.g.cs。
/// 包含：AuthMode 枚举、SpecEndpoints 端点注册表、SpecPorts 端口常量、SpecConfig 配置常量。
/// 这是 Roslyn Analyzer 和业务代码引用端点/端口/配置的唯一来源。
/// </summary>
public static class ManifestGenerator
{
    public static string Generate(SpecDocument spec)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine("// 源: shared-spec.json → api.endpoints + api.websocket + config")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Contract;");
        sb.AppendLine();

        // 1. AuthMode 枚举
        GenerateAuthMode(sb);

        // 2. EndpointSpec record + SpecEndpoints.All
        GenerateSpecEndpoints(sb, spec);

        // 3. SpecPorts（端口常量）
        GenerateSpecPorts(sb, spec);

        // 4. SpecConfig（其它配置常量）
        GenerateSpecConfig(sb, spec);

        return sb.ToString();
    }

    private static void GenerateAuthMode(StringBuilder sb)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// API 端点认证模式。由 shared-spec.json → endpoints[].auth 驱动。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public enum AuthMode");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>需要 Authorization: Bearer {token} 头</summary>");
        sb.AppendLine("    Token = 0,");
        sb.AppendLine("    /// <summary>无需认证，公开访问</summary>");
        sb.AppendLine("    Public = 1,");
        sb.AppendLine("    /// <summary>仅回环地址（127.0.0.1 / ::1）可访问</summary>");
        sb.AppendLine("    Localhost = 2,");
        sb.AppendLine("    /// <summary>WebSocket 专用：认证在首条 JSON 消息中完成，非 HTTP 头</summary>");
        sb.AppendLine("    Message = 3,");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateSpecEndpoints(StringBuilder sb, SpecDocument spec)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// spec 注册的端点规格。由 ManifestGenerator 从 shared-spec.json 生成。");
        sb.AppendLine("/// 供 TokenAuthMiddleware 和 Roslyn Analyzer 使用。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public record EndpointSpec(string Method, string Path, AuthMode Auth, string Description);");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// shared-spec.json 注册的全部端点。Roslyn Analyzer CP100 依据此表校验代码路由。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SpecEndpoints");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly EndpointSpec[] All =");
        sb.AppendLine("    {");

        foreach (var ep in spec.Api.Endpoints)
        {
            string authMode = MapAuthMode(ep.Auth);
            sb.AppendLine($"        new(\"{ep.Method}\", \"{ep.Path}\", AuthMode.{authMode}, \"{EscapeString(ep.Description)}\"),");
        }

        // WebSocket 端点（从 ws://{host}:8443/ws 提取路径 /ws）
        string wsAuthMode = spec.Api.Websocket.AuthMode ?? "message";
        string wsEndpoint = spec.Api.Websocket.Endpoint;
        string wsPath = "/ws"; // 默认
        Uri wsUri = new Uri(wsEndpoint.Replace("{host}", "localhost"));
        wsPath = wsUri.AbsolutePath;
        sb.AppendLine($"        new(\"GET\", \"{wsPath}\", AuthMode.{MapAuthMode(wsAuthMode)}, \"WebSocket 实时推送\"),");

        sb.AppendLine("    };");
        sb.AppendLine();

        // 便捷查询方法
        sb.AppendLine("    /// <summary>按方法和路径查找端点规格（模板参数如 {shareId} 归一化为 {x}）。</summary>");
        sb.AppendLine("    public static EndpointSpec? Find(string method, string normalizedPath)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var ep in All)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (!string.Equals(ep.Method, method, StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("                continue;");
        sb.AppendLine("            // 将 {shareId} 等模板参数归一化为 {x}");
        sb.AppendLine("            var pattern = System.Text.RegularExpressions.Regex.Replace(ep.Path, @\"\\{[^}]+\\}\", \"{x}\");");
        sb.AppendLine("            if (string.Equals(pattern, normalizedPath, StringComparison.OrdinalIgnoreCase))");
        sb.AppendLine("                return ep;");
        sb.AppendLine("        }");
        sb.AppendLine("        return null;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateSpecPorts(StringBuilder sb, SpecDocument spec)
    {
        // 从 config 读取端口常量
        int httpPort = 8443;
        int udpPort = 8450;
        if (spec.Config.TryGetValue("httpPort", out var hp) && hp.ValueKind == JsonValueKind.Number)
        {
            httpPort = hp.GetInt32();
        }

        if (spec.Config.TryGetValue("udpDiscoveryPort", out var up) && up.ValueKind == JsonValueKind.Number)
        {
            udpPort = up.GetInt32();
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 网络端口常量。由 shared-spec.json → config 驱动。");
        sb.AppendLine("/// 代码中禁止硬编码端口数字字面量——应引用此处常量。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SpecPorts");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>服务端 HTTP 监听端口（Phase 0 纯 HTTP，无 TLS）</summary>");
        sb.AppendLine($"    public const int HttpPort = {httpPort};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>UDP 局域网发现服务端口</summary>");
        sb.AppendLine($"    public const int UdpDiscoveryPort = {udpPort};");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateSpecConfig(StringBuilder sb, SpecDocument spec)
    {
        // 读取速率限制配置
        int rateLimit = 60;
        if (spec.Config.TryGetValue("rateLimitPerMinute", out var rl) && rl.ValueKind == JsonValueKind.Number)
        {
            rateLimit = rl.GetInt32();
        }

        // 分块上传配置（消费者：ApiClient / ChunkedUploadService）
        int chunkSize = 4_194_304;
        if (spec.Config.TryGetValue("chunkSize", out var cs) && cs.ValueKind == JsonValueKind.Number)
        {
            chunkSize = cs.GetInt32();
        }

        long chunkedUploadThreshold = 10_485_760;
        if (spec.Config.TryGetValue("chunkedUploadThreshold", out var cut) && cut.ValueKind == JsonValueKind.Number)
        {
            chunkedUploadThreshold = cut.GetInt64();
        }

        int queuePriorityThreshold = 1_048_576;
        if (spec.Config.TryGetValue("queuePriorityThreshold", out var qpt) && qpt.ValueKind == JsonValueKind.Number)
        {
            queuePriorityThreshold = qpt.GetInt32();
        }

        string conflictSuffixPattern = "_冲突_yyyyMMdd_HHmmss";
        if (spec.Config.TryGetValue("conflictSuffixPattern", out var csp) && csp.ValueKind == JsonValueKind.String)
        {
            conflictSuffixPattern = csp.GetString()!;
        }

        int chunkedUploadTimeoutMinutes = 1440;
        if (spec.Config.TryGetValue("chunkedUploadTimeoutMinutes", out var cutm) && cutm.ValueKind == JsonValueKind.Number)
        {
            chunkedUploadTimeoutMinutes = cutm.GetInt32();
        }

        int maxRetryCount = 10;
        if (spec.Config.TryGetValue("maxRetryCount", out var mrc) && mrc.ValueKind == JsonValueKind.Number)
        {
            maxRetryCount = mrc.GetInt32();
        }

        string retryBackoffMs = "1000, 2000, 4000, 8000, 16000, 32000, 60000, 120000, 240000, 300000";
        if (spec.Config.TryGetValue("retryBackoffMs", out var rbm) && rbm.ValueKind == JsonValueKind.Array)
        {
            retryBackoffMs = string.Join(", ", rbm.EnumerateArray().Select(e => e.GetInt32()));
        }

        // 定时全量扫描间隔（消费者：FileWatcherService 兜底定时器 / SyncEngine.FullScanInterval）
        int scanIntervalMinutes = 5;
        if (spec.Config.TryGetValue("scanIntervalMinutes", out var sim) && sim.ValueKind == JsonValueKind.Number)
        {
            scanIntervalMinutes = sim.GetInt32();
        }

        // 保留版本数默认值（消费者：UploadService/ChunkedUploadService 版本裁剪）
        int maxVersionsDefault = 5;
        if (spec.Config.TryGetValue("maxVersionsDefault", out var mvd) && mvd.ValueKind == JsonValueKind.Number)
        {
            maxVersionsDefault = mvd.GetInt32();
        }

        // 家庭 Token 熵（位）（消费者：TokenGenerator 生成字节数 = 熵 / 8）
        int tokenEntropy = 256;
        if (spec.Config.TryGetValue("tokenEntropy", out var te) && te.ValueKind == JsonValueKind.Number)
        {
            tokenEntropy = te.GetInt32();
        }

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 运行时配置常量。由 shared-spec.json → config 驱动。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SpecConfig");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>每设备每分钟 API 调用上限（文件上传/下载不计入）</summary>");
        sb.AppendLine($"    public const int RateLimitPerMinute = {rateLimit};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>速率限制响应头名称</summary>");
        sb.AppendLine("    public const string RetryAfterHeader = \"Retry-After\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>WebSocket 重连最大退避时间（秒）</summary>");
        sb.AppendLine($"    public const int WebSocketReconnectMaxBackoffSeconds = {(spec.Api.Websocket.ReconnectMaxBackoffSeconds ?? 60)};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>WebSocket 心跳间隔（秒）。消费者：WebSocketHeartbeatHostedService</summary>");
        sb.AppendLine($"    public const int PingIntervalSeconds = {spec.Api.Websocket.Heartbeat.PingIntervalSeconds};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>WebSocket Pong 超时（秒）。消费者：WebSocketHandler 心跳检测</summary>");
        sb.AppendLine($"    public const int PongTimeoutSeconds = {spec.Api.Websocket.Heartbeat.PongTimeoutSeconds};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>分块上传每块字节数</summary>");
        sb.AppendLine($"    public const int ChunkSize = {chunkSize};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>文件 ≥ 此字节数使用分块上传，< 此值整文件直传</summary>");
        sb.AppendLine($"    public const long ChunkedUploadThreshold = {chunkedUploadThreshold};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>文件 < 此字节数标记为 High 优先级，优先传输</summary>");
        sb.AppendLine($"    public const int QueuePriorityThreshold = {queuePriorityThreshold};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>冲突副本命名模式（占位符：yyyyMMdd=日期, HHmmss=时间）</summary>");
        sb.AppendLine($"    public const string ConflictSuffixPattern = \"{EscapeString(conflictSuffixPattern)}\";");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>分块上传超时（分钟）。超时未完成则清理临时文件</summary>");
        sb.AppendLine($"    public const int ChunkedUploadTimeoutMinutes = {chunkedUploadTimeoutMinutes};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>HTTP 请求失败最大重试次数，达到后放弃并通知用户</summary>");
        sb.AppendLine($"    public const int MaxRetryCount = {maxRetryCount};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>HTTP 请求失败指数退避序列（毫秒）。第 n 次重试取第 n-1 个值，超出序列长度保持末值</summary>");
        sb.AppendLine($"    public static readonly int[] RetryBackoffMs = {{ {retryBackoffMs} }};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>定时全量扫描间隔（分钟），兜底 FileSystemWatcher 遗漏</summary>");
        sb.AppendLine($"    public const int ScanIntervalMinutes = {scanIntervalMinutes};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>文件版本历史默认保留数</summary>");
        sb.AppendLine($"    public const int MaxVersionsDefault = {maxVersionsDefault};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>家庭 Token 熵（位）。生成字节数 = 熵 / 8</summary>");
        sb.AppendLine($"    public const int TokenEntropy = {tokenEntropy};");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>服务端 Token 文件名</summary>");
        sb.AppendLine("    public const string TokenFileName = \"token.txt\";");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>UDP 发现协议消息</summary>");
        sb.AppendLine("    public const string DiscoveryMessage = \"CLOUDPAN_DISCOVER\";");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string MapAuthMode(string auth) => auth switch
    {
        "token" => "Token",
        "public" => "Public",
        "localhost" => "Localhost",
        "message" => "Message",
        "true" => "Token",    // 兼容旧 boolean 值
        "false" => "Public",
        _ => "Token"
    };

    private static string EscapeString(string s) => s.Replace("\"", "\\\"");
}
