using System.Text;
using System.Text.Json;

namespace CloudPan.CodeGen.Generators;

/// <summary>
/// 从 shared-spec.json 的 settings 段生成 Settings.g.cs。
/// 包含：SettingType/SettingPersistence/SettingGroup 枚举、ServerSettingDef record、
/// SpecSettings（键名常量 + 定义数组 + 查找方法）。设置 UI 与设置服务的唯一事实来源（规则 0）。
/// </summary>
public static class SettingsGenerator
{
    public static string Generate(SpecDocument spec)
    {
        if (spec.Settings == null)
        {
            throw new InvalidOperationException("shared-spec.json 缺少顶层 settings 段");
        }

        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// AUTO-GENERATED from shared-spec.json")
          .AppendLine($"// 版本: {spec.Version}  日期: {spec.Date}")
          .AppendLine("// 源: shared-spec.json → settings")
          .AppendLine("// claude: do not edit this file directly — regenerate with: dotnet run --project CloudPan.CodeGen")
          .AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace CloudPan.Contract;");
        sb.AppendLine();

        GenerateTypeEnum(sb, spec.Settings);
        GeneratePersistenceEnum(sb);
        GenerateGroupEnum(sb, spec.Settings);
        GenerateServerSettingDef(sb);
        GenerateSpecSettings(sb, spec);

        return sb.ToString();
    }

    private static void GenerateTypeEnum(StringBuilder sb, SettingsDef settings)
    {
        // 从 items.type 去重收集
        var types = settings.Items.Select(i => MapType(i.Type)).Distinct().OrderBy(t => t).ToList();
        sb.AppendLine("/// <summary>设置值类型。由 shared-spec.json → settings.items.type 驱动。</summary>");
        sb.AppendLine("public enum SettingType");
        sb.AppendLine("{");
        for (int i = 0; i < types.Count; i++)
        {
            sb.AppendLine($"    {types[i]} = {i},");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GeneratePersistenceEnum(StringBuilder sb)
    {
        sb.AppendLine("/// <summary>设置持久化通道。由 shared-spec.json → settings.items.persistence 驱动。</summary>");
        sb.AppendLine("public enum SettingPersistence");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>启动期参数，存 server-settings.json，重启生效</summary>");
        sb.AppendLine("    Startup = 0,");
        sb.AppendLine("    /// <summary>运行时设置，存 AppConfig 表，立即生效</summary>");
        sb.AppendLine("    AppConfig = 1,");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateGroupEnum(StringBuilder sb, SettingsDef settings)
    {
        sb.AppendLine("/// <summary>设置分组。由 shared-spec.json → settings.groups 驱动。</summary>");
        sb.AppendLine("public enum SettingGroup");
        sb.AppendLine("{");
        for (int i = 0; i < settings.Groups.Count; i++)
        {
            var g = settings.Groups[i];
            sb.AppendLine($"    {Naming.ToPascalCase(g.Id)} = {i},");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static void GenerateServerSettingDef(StringBuilder sb)
    {
        sb.AppendLine("/// <summary>服务端设置项定义。由 SettingsGenerator 从 shared-spec.json 生成。</summary>");
        sb.AppendLine("public record ServerSettingDef(string Key, string Label, string Description,");
        sb.AppendLine("    SettingType Type, string Default, SettingPersistence Persistence,");
        sb.AppendLine("    bool RestartRequired, SettingGroup Group, int? Min, int? Max, bool IsPath, string? Action);");
        sb.AppendLine();
    }

    private static void GenerateSpecSettings(StringBuilder sb, SpecDocument spec)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// 服务端设置目录。键名、默认值、元数据的唯一事实来源（规则 0）。");
        sb.AppendLine("/// 设置 UI 与设置服务从本类读取定义，禁止在代码中手写设置键字符串。");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class SpecSettings");
        sb.AppendLine("{");
        sb.AppendLine("    public static class Keys");
        sb.AppendLine("    {");
        foreach (var item in spec.Settings!.Items)
        {
            sb.AppendLine($"        /// <summary>{Escape(item.Label)}</summary>");
            sb.AppendLine($"        public const string {Naming.ToPascalCase(item.Key)} = \"{item.Key}\";");
        }
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    public static readonly ServerSettingDef[] All =");
        sb.AppendLine("    {");
        foreach (var item in spec.Settings.Items)
        {
            sb.AppendLine($"        new(\"{item.Key}\", \"{Escape(item.Label)}\", \"{Escape(item.Description)}\", " +
                          $"SettingType.{MapType(item.Type)}, \"{Escape(ResolveDefault(spec, item))}\", " +
                          $"{MapPersistence(item.Persistence)}, {Bool(item.RestartRequired)}, " +
                          $"SettingGroup.{Naming.ToPascalCase(item.Group)}, " +
                          $"{NullableInt(item.Min)}, {NullableInt(item.Max)}, {Bool(item.IsPath ?? false)}, " +
                          $"{NullableString(item.Action)}),");
        }
        sb.AppendLine("    };");
        sb.AppendLine();

        sb.AppendLine("    /// <summary>按键名查找设置定义。未找到抛 KeyNotFoundException。</summary>");
        sb.AppendLine("    public static ServerSettingDef Get(string key)");
        sb.AppendLine("    {");
        sb.AppendLine("        foreach (var def in All)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (string.Equals(def.Key, key, StringComparison.Ordinal))");
        sb.AppendLine("            {");
        sb.AppendLine("                return def;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        throw new KeyNotFoundException($\"设置键未在 shared-spec.json 注册: {key}\");");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string MapType(string type) => type switch
    {
        "int" => "Int",
        "string" => "String",
        "secret" => "Secret",
        _ => throw new InvalidOperationException($"settings.items.type 不支持: {type}")
    };

    private static string MapPersistence(string persistence) => persistence switch
    {
        "startup" => "SettingPersistence.Startup",
        "appconfig" => "SettingPersistence.AppConfig",
        _ => throw new InvalidOperationException($"settings.items.persistence 不支持: {persistence}")
    };

    /// <summary>解析 defaultRef（如 "config.httpPort"）到 config 字典取值；无 defaultRef 返回空串。</summary>
    private static string ResolveDefault(SpecDocument spec, SettingsItemDef item)
    {
        if (string.IsNullOrEmpty(item.DefaultRef))
        {
            return "";
        }

        // 格式 "config.httpPort" → 键 "httpPort"
        string[] parts = item.DefaultRef.Split('.');
        string configKey = parts.Length == 2 ? parts[1] : item.DefaultRef;

        if (spec.Config.TryGetValue(configKey, out JsonElement val))
        {
            return val.ValueKind switch
            {
                JsonValueKind.Number => val.GetInt32().ToString(),
                JsonValueKind.String => val.GetString() ?? "",
                _ => val.GetRawText()
            };
        }

        throw new InvalidOperationException($"defaultRef 指向的 config 键不存在: {item.DefaultRef}");
    }

    private static string Bool(bool value) => value ? "true" : "false";

    private static string NullableInt(int? value) => value.HasValue ? value.Value.ToString() : "null";

    private static string NullableString(string? value) => value == null ? "null" : $"\"{Escape(value)}\"";

    private static string Escape(string s) => s.Replace("\"", "\\\"");
}
